
development:
  adapter: postgresql
  encoding: unicode
  database: adventure_library_development
  pool: 5
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: adventure_library_test
  pool: 5
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: adventure_library_production
  pool: 5
  host: localhost
  port: 5432
